name: STM32 CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Restore ARM toolchain cache
      id: cache-toolchain
      uses: actions/cache@v4
      with:
        path: toolchain
        key: ${{ runner.os }}-arm-toolchain-v14
        restore-keys: |
          ${{ runner.os }}-arm-toolchain-

    - name: Download and extract ARM toolchain
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      run: |
        curl -L https://developer.arm.com/-/media/Files/downloads/gnu/14.3.rel1/binrel/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi.tar.xz \
          -o toolchain.tar.xz
        mkdir -p toolchain
        tar -xf toolchain.tar.xz -C toolchain

    - name: Add ARM toolchain to PATH
      run: echo "${{ github.workspace }}/toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH
    
    - name: Verify toolchain
      run: arm-none-eabi-gcc --version
      
    - name: Build Firmvare
      run: |
        cmake --preset PrintSpider_stm32
        cmake --build --preset build-fw

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ github.sha }}
        path: |
          ./build/*.bin
          ./build/*.hex
          ./build/*.elf