name: STM32 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install ARM toolchain and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make

    - name: Build Firmvare
      run: |
        mkdir build
        cmake ./CMakeLists.txt -DCMAKE_BUILD_TYPE=Release -G Ninja -B ./build/Release
        ninja -C ./build/Release

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/Release/*.bin