name: STM32 CI

env:
  PROJECT_NAME: ${{ github.event.repository.name }}

on:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build          # runs after build
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ github.sha }}
          path: |
            build/*.bin
            build/*.hex
            build/*.elf
            build/build-host/tests/Testing